export default defineAppConfig({
  ui: {
    icons: {
      arrowLeft: 'i-fluent-arrow-left-24-regular',
      arrowRight: 'i-fluent-arrow-right-24-regular',
      arrowUp: 'i-fluent-arrow-up-24-regular',
      arrowDown: 'i-fluent-arrow-down-24-regular',
      caution: 'i-fluent-error-circle-24-regular',
      check: 'i-fluent-checkmark-24-regular',
      chevronDoubleLeft: 'i-fluent-arrow-previous-24-regular',
      chevronDoubleRight: 'i-fluent-arrow-next-24-regular',
      chevronDown: 'i-fluent-chevron-down-24-regular',
      chevronLeft: 'i-fluent-chevron-left-24-regular',
      chevronRight: 'i-fluent-chevron-right-24-regular',
      chevronUp: 'i-fluent-chevron-up-24-regular',
      close: 'i-fluent-dismiss-24-regular',
      copy: 'i-fluent-copy-24-regular',
      copyCheck: 'i-fluent-checkmark-24-regular',
      dark: 'i-fluent-weather-moon-24-regular',
      drag: 'i-fluent-re-order-dots-vertical-24-regular',
      ellipsis: 'i-fluent-more-horizontal-24-regular',
      error: 'i-fluent-dismiss-circle-24-regular',
      external: 'i-fluent-open-24-regular',
      eye: 'i-fluent-eye-24-regular',
      eyeOff: 'i-fluent-eye-off-24-regular',
      file: 'i-fluent-document-24-regular',
      folder: 'i-fluent-folder-24-regular',
      folderOpen: 'i-fluent-folder-open-24-regular',
      hash: 'i-fluent-number-symbol-24-regular',
      info: 'i-fluent-info-24-regular',
      light: 'i-fluent-weather-sunny-24-regular',
      loading: 'i-fluent-arrow-clockwise-24-regular',
      menu: 'i-fluent-navigation-24-regular',
      minus: 'i-fluent-subtract-24-regular',
      panelClose: 'i-fluent-panel-left-contract-24-regular',
      panelOpen: 'i-fluent-panel-left-expand-24-regular',
      plus: 'i-fluent-add-24-regular',
      reload: 'i-fluent-arrow-counterclockwise-24-regular',
      search: 'i-fluent-search-24-regular',
      stop: 'i-fluent-stop-24-regular',
      success: 'i-fluent-checkmark-circle-24-regular',
      system: 'i-fluent-desktop-24-regular',
      tip: 'i-fluent-lightbulb-24-regular',
      upload: 'i-fluent-arrow-upload-24-regular',
      warning: 'i-fluent-warning-24-regular',
    },
  },
})
